### PR TITLE
Reenabled the test

### PR DESCRIPTION
**Pull request by Crazi12345**
Reenabled the test, since we fixed it

### CODE REVIEW

**Review by v-nemeth — COMMENTED** [review]
k

**Comment by mathiasgredal** [comment]
I don't know what computer you have, but mine just hangs seemingly forever

**Comment by marc7636** [comment]
image
Det samme gør GitHub

**Comment by Crazi12345** [comment]
it should be fixed now, some bad values made it take forever

**Review by MagnusHJensen — APPROVED** [review]
Test runs fine, can't talk for what the test actual tests etc.

**Comment by MagnusHJensen** [comment]
Guess this doesn't matter since the self-approved #230 pr, that also includes re-enabling this test 🤷

**Review by jfriisj — APPROVED** [review]
Looks good

**Review by emma7636 — CHANGES_REQUESTED** [review]
Latest system test is still hanging indefinitely

**Comment by marc7636** [comment]
Seeing several NullReferenceExceptions in async threads, probably a good place to start

**Comment by marc7636** [comment]
Turns out the NullReferenceExceptions came from our code, this should now be fixed and merged with the main branch

**Comment by marc7636** [comment]
Main branch is currently working, please hurry before it breaks again

**Pull request closed without merging**
