### PR TITLE
Create database on test runner

### PR DESCRIPTION
**Pull request by mathiasgredal**
This adds a database to the test runner

### CODE REVIEW

**Comment by The0mikkel** [comment]
Is this to make sure, that all migrations work?

**Comment by The0mikkel** [comment]
If we are going to the extent, to test the database, then we should ensure, that a properties file is included in the test.
As well as maybe run the whole Junit test suite every time, even though that might end to even more failed tests.

The compile-test and all other should run on pull requests to main and when you push to main, currently it is only set up to run on pull-requests

**Comment by mathiasgredal** [comment]
Our branch have unit tests that depends on having a database. This PR gives the testrunner a database. It only verifies that migrations work if the earlier migration files haven’t been touched(although this should also be tested). What properties file should be included in the test?.

**Comment by The0mikkel** [comment]
> Our branch(SEM/main) have unit tests that depends on having a database. This PR gives the testrunner a database  

The "testrunner" is not a test runner in the sense you probably are thinking of.
The GitHub action, that you have changed, only compiles the whole program, to ensure that no errors occur when compiling the program. This is done, to ensure, that updates do not break the program for other groups, as failing to compile would for most of our collaborators result in the code not being runnable in any format.

If we would like to have a GitHub action, that results in a "check" on pull requests, to automatically run our unit tests, then I would suggest it being brought up in the more public forum, where all opinions on this can be heard, as a more automatic pipeline, with automatic tests, is not something we have been really taught - But we have been introduced to the DevOps world, so it could be possible to implement here

I would love the idea of the test suite being run every time we make a pull request to ensure the program works. But some groups may not have their tests fully developed.

**Comment by mathiasgredal** [comment]
The `mvn verify` command does run the tests. Our maven config was broken, which caused the tests to not run. I have fixed the maven configuration, so now the tests are run.

**Comment by The0mikkel** [comment]
> The `mvn verify` command does run the tests. Our maven config was broken, which caused the tests to not be run. I have fixed the maven configuration, so now the tests are run.
> 
> ```
> Tests run: 140, Failures: 7, Errors: 18, Skipped: 0
> ```

I didn't catch that `mvn verify` actually runs the tests. It was supposed to actually only compile the program  
I will try to update the system, as I would like that to be spread into multiple Github Actions:
1. Compile test
2. Migration test
3. Unit / Feature tests

Or do you believe this would be overkill / not necessary?

**Comment by The0mikkel** [comment]
> It would be quite unnecessary, since the 3 processes depend on each other. Compilation -> Migration -> Testing

Alright, but I would like to rename this action then.

I'm going to do some small changes.

**Comment by The0mikkel** [comment]
I have moved it into two distinct tests, a compile and a verify  
The compiled test is faster and allows specifically to check if the compile fails  
The verify test is slower and ensures that new versions of the software pass all tests. This may fail if groups haven't completed their tests.

**Review by The0mikkel — APPROVED** [review]

**Pull request merged**
