### PR TITLE
PIM2 - Added TokenParameter Tests

### PR DESCRIPTION
**Pull request by MagnusHJensen**
We did also modify the migration file. (I know it was stated not to touch, but since no actual migration has been done I thought it was going to be okay.)

The reason is, postgres doesn't really like table names with capital letters 😅

### CODE REVIEW

**Review by mathiasgredal — DISMISSED** [review]

**Review by emma7636 — CHANGES_REQUESTED** [review]
If you are going to import powermock, please make sure it works
image

**Comment by MagnusHJensen** [comment]
> If you are going to import powermock, please make sure it works image

It does work, locally.

I'm assuming it fails on the tests, since the tests is ran with the pom.xml located on the main branch, therefore it doesn't have powermock, we reference it, hence it breaks trying to run tests.

I'm fine with whenever this get's merged that an instant revert can happen in case it doesn't work, but I'm pretty confident in that it does.

**Comment by marc7636** [comment]
Tried pulling your branch to test it, doesn't seem to work.
image

**Comment by marc7636** [comment]
Also ran into this error
image

**Pull request closed without merging**
